# Site settings
title: Effortless Serverless
email: contact@effortless-serverless.com
description: Serverless stories
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://effortless-serverless.com" # the base hostname & protocol for your site
enable_retina: false
permalink: :title
nav_list:
  Home : ['Home', '/', 'fa-home']
  About : ['About', '/about', 'fa-anchor']
  Book : ['Book', '/book', 'fa-book']
single_footer: '<p>Effortless Serverless blog &copy; 2018 <a href="/">latest posts</a></p>'
footer_links:
    Blog: ['Blog', '/']
    About: ['About', '/about']


# Build settings
# markdown: kramdown
