# Site settings
title: Serverless.Pub
email: contact@serverless.pub
description: Short stories from around the campfire for a fellow serverless explorer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://serverless.pub" # the base hostname & protocol for your site
enable_retina: false
permalink: :title/
nav_list:
  Home : ['Home', '/', 'fa-home']
  About : ['About', '/about', 'fa-anchor']
  Book : ['Book', '/book', 'fa-book']
single_footer: '<p>Serverless.Pub &copy; 2018 <a href="/">latest posts</a></p>'
footer_links:
  Blog: ['Blog', '/']
  About: ['About', '/about']


# Build settings
# markdown: kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'syntax'

version: 10
